{"name": "TC-18: Повторное применение купона", "status": "failed", "statusDetails": {"message": "AssertionError: Купон 'GIVEMEHALYAVA' применился повторно! Найдена строка купона.", "trace": "self = <tests.test_coupon_flow.TestCouponFlow object at 0x0000023A1F1E7230>, browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9b051187ed57ac827f95a530bf11b2c8\")>\npreparing_cart = {'cart_page': <pages.cart_page.CartPage object at 0x0000023A1F3A87D0>, 'first_pizza_name': 'Пицца «Как у бабушки»', 'second_pizza_name': 'Пицца «4 в 1»'}\n\n    @allure.story(\"Неуспешное применение купона\")\n    @allure.title(\"TC-18: Повторное применение купона\")\n    def test_reuse_coupon(self, browser, preparing_cart):\n        coupon_page = CouponPage(browser)\n        auth_page = AuthPage(browser)\n        preparing_cart['cart_page'].open_cart()\n        (auth_page.go_to_auth_page()\n         .fill_login_form(\"qweqwe123\", \"123\")\n         .submit_login())\n        CartPage(browser).open_cart()\n        coupon_page.enter_coupon(\"GIVEMEHALYAVA\").apply_coupon()\n        (auth_page.proceed_to_payment())\n        time.sleep(3)\n        auth_page.accept_terms()\n        auth_page.place_order()\n        main_page = MainPage(browser)\n        main_page.open_url()\n        main_page.hover_pizza()\n        main_page.click_add_to_cart()\n        CartPage(browser).open_cart()\n        coupon_page.enter_coupon(\"GIVEMEHALYAVA\").apply_coupon()\n>       coupon_page.verify_coupon_field(\"GIVEMEHALYAVA\")\n\ntests\\test_coupon_flow.py:85: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.coupon_page.CouponPage object at 0x0000023A1F2AA850>, coupon_code = 'GIVEMEHALYAVA'\n\n    @allure.step(\"Проверить, что купон не применился повторно\")\n    def verify_coupon_field(self, coupon_code=\"GIVEMEHALYAVA\"):\n        self.wait.until(EC.visibility_of_element_located(CouponLocators.COUPON_ROW))\n>       raise AssertionError(f\"Купон '{coupon_code}' применился повторно! Найдена строка купона.\")\nE       AssertionError: Купон 'GIVEMEHALYAVA' применился повторно! Найдена строка купона.\n\npages\\coupon_page.py:104: AssertionError"}, "steps": [{"name": "Открыть корзину", "status": "passed", "start": 1755875531739, "stop": 1755875532364}, {"name": "Перейти в 'Мой аккаунт'", "status": "passed", "start": 1755875532365, "stop": 1755875532964}, {"name": "Авторизоваться пользователем qweqwe123", "status": "passed", "parameters": [{"name": "username", "value": "'qweqwe123'"}, {"name": "password", "value": "'123'"}], "start": 1755875532964, "stop": 1755875533250}, {"name": "Нажать кнопку входа", "status": "passed", "start": 1755875533250, "stop": 1755875533406}, {"name": "Открыть корзину", "status": "passed", "start": 1755875533406, "stop": 1755875534530}, {"name": "Ввести код купона ''GIVEMEHALYAVA''", "status": "passed", "parameters": [{"name": "coupon", "value": "'GIVEMEHALYAVA'"}], "start": 1755875534530, "stop": 1755875535051}, {"name": "Применить купон", "status": "passed", "start": 1755875535051, "stop": 1755875537253}, {"name": "Перейти к оплате", "status": "passed", "start": 1755875537253, "stop": 1755875537857}, {"name": "Принять условия соглашения", "status": "passed", "start": 1755875540858, "stop": 1755875541069}, {"name": "Подтвердить заказ", "status": "passed", "start": 1755875541069, "stop": 1755875541202}, {"name": "Открыть домашнюю страницу", "status": "passed", "start": 1755875541202, "stop": 1755875541711}, {"name": "Навести курсор на пиццу и проверить кнопку 'В корзину'", "status": "passed", "start": 1755875541712, "stop": 1755875544195}, {"name": "Нажать 'В корзину'", "status": "passed", "start": 1755875544195, "stop": 1755875544333}, {"name": "Открыть корзину", "status": "passed", "start": 1755875544334, "stop": 1755875544778}, {"name": "Ввести код купона ''GIVEMEHALYAVA''", "status": "passed", "parameters": [{"name": "coupon", "value": "'GIVEMEHALYAVA'"}], "start": 1755875544779, "stop": 1755875545114}, {"name": "Применить купон", "status": "passed", "start": 1755875545114, "stop": 1755875547254}, {"name": "Проверить, что купон не применился повторно", "status": "failed", "statusDetails": {"message": "AssertionError: Купон 'GIVEMEHALYAVA' применился повторно! Найдена строка купона.\n", "trace": "  File \"C:\\course_work\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\course_work\\pages\\coupon_page.py\", line 104, in verify_coupon_field\n    raise AssertionError(f\"Купон '{coupon_code}' применился повторно! Найдена строка купона.\")\n"}, "parameters": [{"name": "coupon_code", "value": "'GIVEMEHALYAVA'"}], "start": 1755875547254, "stop": 1755875547311}], "start": 1755875531739, "stop": 1755875547313, "uuid": "9d444d79-55b7-4184-85c3-f7554b416bb1", "historyId": "41400aa66cb1088df25d7f467d1363b5", "testCaseId": "41400aa66cb1088df25d7f467d1363b5", "fullName": "tests.test_coupon_flow.TestCouponFlow#test_reuse_coupon", "labels": [{"name": "feature", "value": "Флоу с кодом купона"}, {"name": "story", "value": "Неуспешное применение купона"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_coupon_flow"}, {"name": "subSuite", "value": "TestCouponFlow"}, {"name": "host", "value": "DESKTOP-CASI0Q3"}, {"name": "thread", "value": "10312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_coupon_flow"}]}